### ISSUE TITLE
Lossy compression?

### ISSUE THREAD

**Issue by ripefig** [Huluti/ImCompressor#7] opened 2019-10-11 14:34 UTC
I know it says "lossless", but lossy would be much more useful since the common case for compression is to prepare the image for sharing. Lossless only shaves off about 10% off most images, and it does so very slowly. Thus is doesn't really do much for most users.

**Comment by ripefig** [comment] 2019-10-11 14:38
some compression utilities:
https://pngquant.org/
https://css-ig.net/pingo

**Comment by Huluti** [comment] 2019-10-11 14:53
Thank's for the suggestion. I'm thinking of how to implement this feature. Duplicate of #6.

**Closed by Huluti** 2019-10-11 14:53 UTC

**Comment by ripefig** [comment] 2019-10-11 14:58
@Huluti 
Another optimizer:
https://saerasoft.com/caesium/
